## Linter GitHub Actions ##
name: Linting-code
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [ feature, master ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Terraform
    # Set the agent to run on
    runs-on: ubuntu-20.04
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      ################################
      # Run Linter against code base #
      ################################
      - name: Terraform Linter
        uses: docker://github/super-linter:v2.1.1
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TERRAFORM: true
